#!/usr/bin/env python3
"""Build only the public design exploration, with no production runtime bindings."""
from pathlib import Path
import json, re, shutil
from html import escape

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'design-lab'
OUT=ROOT/'design-dist'
CONCEPTS=json.loads((SOURCE/'concepts.json').read_text())
if OUT.is_symlink():raise SystemExit('Refusing to replace a symlink at design-dist')
if OUT.exists():shutil.rmtree(OUT)
OUT.mkdir()
(OUT/'assets').mkdir()
for name in ['concepts.css','explore.css','explore.js','concepts.json']:
 shutil.copy2(SOURCE/name,OUT/name)
shutil.copytree(SOURCE/'assets',OUT/'assets',dirs_exist_ok=True)
shutil.copy2(ROOT/'logo.svg',OUT/'logo.svg')
shutil.copy2(ROOT/'nate.jpg',OUT/'assets/nate.jpg')
shutil.copy2(ROOT/'assets/josh.png',OUT/'assets/josh.png')
# The complete initial direction is retained as one option in the exploration.
shutil.copytree(SOURCE/'editorial',OUT/'editorial')
FONTS='https://fonts.googleapis.com/css2?family=Archivo+Black&family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,500;1,400&family=Space+Grotesk:wght@400;500;600;700&display=swap'
def dock(current):
 links=''.join(f'<a href="/{c["id"]}/" aria-label="{c["number"]}: {c["name"]}"'+(' aria-current="page"' if c['id']==current else '')+f'>{c["number"]}</a>' for c in CONCEPTS)
 opts=''.join(f'<option value="{c["id"]}"'+(' selected' if c['id']==current else '')+f'>{c["number"]} · {c["name"]}</option>' for c in CONCEPTS)
 c=next(c for c in CONCEPTS if c['id']==current)
 return f'<nav class="direction-dock" aria-label="Design directions"><a class="dock-home" href="/directions.html">↖ All directions</a><div class="dock-numbers">{links}</div><label class="dock-select"><span class="sr-only">Choose a design direction</span><select data-direction-select>{opts}</select></label><span class="dock-name">{c["short"]}</span><a class="dock-compare" href="/compare.html?left={current}&amp;right={CONCEPTS[(CONCEPTS.index(c)+1)%10]["id"]}">Compare ↗</a></nav>'
def head(title,styles='concepts.css'):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{title} · East Bay Projects Design Study</title><meta name="description" content="Explore ten design directions for East Bay Projects. A separate test site for comparing styles and approaches."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="{escape(FONTS,quote=True)}" rel="stylesheet"><link href="/{styles}" rel="stylesheet"><link href="/explore.css" rel="stylesheet"><script>if(new URLSearchParams(location.search).has('embed'))document.documentElement.classList.add('embedded');</script><script src="/explore.js" defer></script></head>'''
def nav():return '''<a class="skip" href="#main">Skip to content</a><header><div class="shell topbar"><a class="brand" href="#main" aria-label="East Bay Projects home"><span>east bay</span><span>projects.</span></a><nav class="site-nav" aria-label="Main navigation"><a href="#work">Our work</a><a href="#services">What we do</a><a href="#studio">The studio</a><a href="#contact" class="nav-cta">Start a project ↗</a></nav></div></header>'''
DESCRIPTION='A business and product partner, paired with a senior engineer. We work with your team to reach people, improve operations, and bring new ideas to life.'
cta='<div class="hero-cta"><a class="primary" href="#contact">Let’s build something <span aria-hidden="true">↗</span></a><a class="link" href="#work">Explore the work <span aria-hidden="true">↓</span></a></div>'
diagram='''<svg viewBox="0 0 500 360" role="img" aria-label="One project team connects strategy, design, engineering, and delivery"><g fill="none" stroke="currentColor" stroke-width="1"><rect x="155" y="125" width="190" height="110"/><rect x="20" y="20" width="170" height="65"/><rect x="310" y="20" width="170" height="65"/><rect x="20" y="275" width="170" height="65"/><rect x="310" y="275" width="170" height="65"/><path d="M105 85v40h50M395 85v40h-50M105 275v-40h50M395 275v-40h-50"/><circle cx="250" cy="180" r="105" stroke-dasharray="3 7" opacity=".35"/></g><g fill="currentColor" font-family="IBM Plex Mono,monospace" text-anchor="middle"><text x="105" y="59" font-size="14">01 STRATEGY</text><text x="395" y="59" font-size="14">02 DESIGN</text><text x="105" y="313" font-size="14">03 ENGINEERING</text><text x="395" y="313" font-size="14">04 DELIVERY</text><text x="250" y="166" font-size="12">ONE TEAM.</text><text x="250" y="194" font-size="22">YOUR PROJECT.</text></g></svg>'''
heroes={
'swiss':f'''<section class="hero swiss-hero"><div class="shell"><div class="swiss-index kicker"><span>Independent design &amp; technology</span><span>Austin / Washington, DC</span></div><h1>Clarity,<br>by <span>design.</span></h1><div class="swiss-bottom"><p class="hero-copy">{DESCRIPTION}</p><div><p class="kicker">Websites.<br>Software.<br>Civic platforms.</p><a class="primary" href="#work">Selected work <span>↘</span></a></div></div></div></section>''',
'commons':f'''<section class="hero commons-hero"><div class="shell commons-grid"><div><p class="kicker">Good for business. Good for the world around it.</p><h1>Make good<br>things<br><em>happen.</em></h1><p class="hero-copy">{DESCRIPTION}</p>{cta}</div><div class="commons-orbit" aria-label="Businesses, founders, and civic teams share a focus on useful work"><div class="orbit-ring"></div><div class="orbit-ring"></div><div class="orbit-core">Made<br>to matter.</div><span class="orbit-label a">Businesses ↗</span><span class="orbit-label b">Founders ↗</span><span class="orbit-label c">Civic &amp; campaigns ↗</span></div></div></section><div class="commons-strip"><span>Thoughtful design</span><span>Useful technology</span><span>Shared progress</span></div>''',
'fieldnotes':f'''<section class="hero field-hero"><div class="shell field-grid"><div><p class="kicker">Field notes from an independent studio</p><h1>A small team.<br>For the<br><em>big picture.</em></h1><p class="hero-copy">{DESCRIPTION}</p>{cta}</div><div class="field-collage"><figure class="field-print"><img src="/assets/work/seamaphore.webp" width="500" height="500" alt="Seamaphore website"><figcaption>01 — Seamaphore / San Francisco</figcaption></figure><figure class="field-print"><img src="/assets/work/brown-for-austin.webp" width="500" height="500" alt="Brown for Austin campaign website"><figcaption>02 — Civic work / Austin</figcaption></figure><span class="field-caption">A few things<br>we’ve put<br>into the world.</span></div></div></section>''',
 'terminal':f'''<section class="hero terminal-hero"><div class="shell"><div class="terminal-grid"><div><p class="kicker">East Bay Projects / Design + engineering</p><h1>BUILD<br>SOMETHING<br><span>THAT WORKS.</span></h1><p class="hero-copy">{DESCRIPTION}</p>{cta}</div><div class="brief-terminal"><div class="terminal-bar"><span>project_brief.txt</span><span>EBP / 001</span></div><div class="terminal-body"><p class="prompt">$ choose a starting point_</p><div class="brief-output" data-brief-output role="status">PROJECT: A better website\n\nAudience → Your next customer\nApproach → A clear story, fast pages,\n           a useful next step.\nTeam → Design + engineering + delivery</div><div class="brief-options" role="group" aria-label="Explore a project brief"><button data-brief="websites" aria-pressed="true">01 WEBSITES</button><button data-brief="software" aria-pressed="false">02 SOFTWARE</button><button data-brief="civic" aria-pressed="false">03 CIVIC</button></div></div></div></div><div class="terminal-path">IDEA / SCOPE / DESIGN / BUILD / LAUNCH</div></div></section>''',
'poster':f'''<section class="hero poster-hero"><div class="shell"><p class="kicker">East Bay Projects — Design. Technology. Action.</p><div class="poster-stamp" aria-hidden="true"></div><h1><span>BIG IDEAS.</span><span>REAL</span><span>IMPACT.</span></h1><div class="poster-bottom"><p class="hero-copy">{DESCRIPTION}</p><a class="primary" href="#work">See what we make <span>↗</span></a></div></div></section>''',
'gallery':f'''<section class="hero gallery-hero"><img class="gallery-bg" data-gallery-image src="/assets/work/seamaphore.webp" width="1600" height="1000" alt="Seamaphore maritime technology website"><div class="gallery-overlay"></div><div class="shell gallery-message"><p class="kicker">Independent minds. Real-world work.</p><h1>The work<br>speaks for itself.</h1><p class="hero-copy">{DESCRIPTION}</p>{cta}<div class="gallery-control"><div><span class="kicker" data-gallery-category>01 / Brand &amp; website</span><strong data-gallery-title>Seamaphore</strong></div><div class="gallery-buttons" role="group" aria-label="Choose the featured project"><button data-gallery="0" aria-label="Show Seamaphore" aria-pressed="true">01</button><button data-gallery="1" aria-label="Show Brown for Austin" aria-pressed="false">02</button><button data-gallery="2" aria-label="Show Austin Tax Rate Election" aria-pressed="false">03</button></div></div></div></section>''',
'blueprint':f'''<section class="hero blue-hero"><div class="shell"><div class="blue-grid"><div><p class="kicker">East Bay Projects / Digital works</p><h1>Your general<br>contractor<br><em>for digital.</em></h1><p class="hero-copy">{DESCRIPTION}</p>{cta}</div><div class="blue-diagram"><div class="diagram-head"><span>PROJECT DELIVERY PLAN</span><span>EBP–001</span></div>{diagram}<div class="diagram-foot"><span>RESPONSIBILITY: END TO END</span><span>SCOPE: AGREED UPFRONT</span></div></div></div><div class="blue-byline"><span>WEBSITES / SOFTWARE / CIVIC PLATFORMS</span><span>AUSTIN + WASHINGTON, DC</span></div></div></section>''',
'play':'''<section class="hero play-hero"><div class="shell play-grid"><div><p class="kicker">An independent studio with a practical streak</p><h1>Serious craft.<br>A little<br><em>unexpected.</em></h1><div class="audience-options" role="group" aria-label="What kind of team are you?"><button data-audience="business" aria-pressed="true">A business</button><button data-audience="founder" aria-pressed="false">A founder</button><button data-audience="civic" aria-pressed="false">A civic team</button></div><p class="hero-copy" data-audience-copy role="status">Make your digital presence feel as good as the work you do. We bring thoughtful design, senior engineering, and a clear path to launch.</p>'''+cta+'''</div><div class="play-art"><div class="play-shape" aria-hidden="true"></div><figure class="play-shot"><img src="/assets/work/seamaphore.webp" width="600" height="500" alt="Seamaphore website, a project by the studio"></figure><span class="play-sticker">Good ideas.<br>Real things.<br>↗</span></div></div></section>''',
'heritage':f'''<section class="hero heritage-hero"><div class="shell heritage-grid"><div><p class="kicker">An independent design &amp; technology practice</p><h1>Built on trust.<br>Designed<br><em>to last.</em></h1><p class="hero-copy">{DESCRIPTION}</p>{cta}<div class="heritage-rule">EXPERIENCED HANDS. THOUGHTFUL WORK.</div></div><figure class="heritage-frame"><img src="/assets/work/brown-for-austin.webp" width="600" height="700" alt="Brown for Austin campaign website"><figcaption>SELECTED WORK / BROWN FOR AUSTIN<br>A platform for public purpose.</figcaption></figure></div></section>'''
}
projects=[
 ('seamaphore','Seamaphore','Brand &amp; website','https://www.seamaphore.com/','seamaphore.webp','A distinctive digital home for a maritime technology incubator at the edge of San Francisco Bay.'),
 ('brown','Brown for Austin','Civic &amp; campaigns','https://brownforaustind1.com/','brown-for-austin.webp','A city council campaign’s digital front door, bringing its story, donations, and volunteer signups together.'),
 ('software','Nate’s Software','Independent product','https://nates-software.com/','', 'A software emporium with a playful desktop interface. Discover, explore, and build on independent software.'),
 ('tax','Austin Tax Rate Election','Civic &amp; public data','https://austintaxrateelection.com/','austin-tax-election.webp','Making a complicated ballot question easier to understand through clear information and accessible public data.')
]
def project_markup(p):
 key,name,tag,url,img,desc=p
 art=f'<img src="/assets/work/{img}" alt="{name} website" width="1440" height="1000" loading="lazy">' if img else '''<div class="software-window" aria-hidden="true"><div class="software-bar">⚡ Nate’s Software</div><div class="software-body"><img src="/assets/work/nates-shopkeeper.webp" alt="" width="100" height="100" loading="lazy"><div><strong>A home for<br>software<br>enthusiasts.</strong><p>Make something. Try something.</p></div></div><div class="software-foot">Independent software. Endless possibilities.</div></div>'''
 return f'<article class="work-item"><a class="project-visual {key}" href="{url}" target="_blank" rel="noopener noreferrer" aria-label="Visit {name} (opens in a new tab)">{art}<span aria-hidden="true">↗</span></a><div class="project-caption"><h3><a href="{url}" target="_blank" rel="noopener noreferrer">{name}</a></h3><p class="kicker">{tag}</p></div><p class="project-desc">{desc}</p></article>'
work='''<section class="chapter work" id="work"><div class="shell"><div class="chapter-head"><div><p class="kicker">01 / Selected work</p><h2>Different worlds.<br>The same care.</h2></div><p>Brand websites, independent products, and civic platforms. Real projects, made for the people who use them.</p></div><div class="work-grid">'''+''.join(project_markup(p) for p in projects)+'''</div><div class="more-work"><span>Also from our portfolio</span><div><a href="https://pertronixbrands.com/" target="_blank" rel="noopener noreferrer">PerTronix Brands ↗</a><a href="https://www.austinsheatingandac.com/" target="_blank" rel="noopener noreferrer">Austin’s Heating &amp; AC ↗</a><a href="https://studio-680.com/" target="_blank" rel="noopener noreferrer">Studio 680 ↗</a><a href="https://natemcguire.com/" target="_blank" rel="noopener noreferrer">Nate McGuire ↗</a></div></div></div></section>'''
services='''<section class="chapter services" id="services"><div class="shell"><div class="chapter-head"><div><p class="kicker">02 / What we help you do</p><h2>Move the work<br>forward.</h2></div><p>One team connects the business problem to the working solution. For independent businesses, founders, and civic organizations.</p></div><div class="service-grid">
<article class="service-card"><span class="kicker">01</span><h3>Reach the<br>right people.</h3><p>Make your story clear and give people a useful next step. Turn interest into an inquiry, a purchase, a donation, or a signup.</p><ul><li>Positioning &amp; brand websites</li><li>Campaign pages &amp; e-commerce</li><li>Lead capture &amp; follow-up</li></ul></article>
<article class="service-card"><span class="kicker">02</span><h3>Make the<br>work flow.</h3><p>Get close to how your team works. Connect the systems, reduce repetitive tasks, and build tools people can use every day.</p><ul><li>Workflow discovery &amp; internal tools</li><li>Integrations &amp; practical AI</li><li>Reporting &amp; automation</li></ul></article>
<article class="service-card"><span class="kicker">03</span><h3>Launch<br>what’s next.</h3><p>Turn an idea into something real. Test a new product, launch a public initiative, or build the application your team has been missing.</p><ul><li>Product strategy &amp; prototypes</li><li>Web &amp; mobile applications</li><li>Civic platforms &amp; public data</li></ul></article></div><p class="scope-note">Start with one useful project. Agree on the scope and what success looks like. Build from there.</p></div></section>'''
process='''<section class="chapter process"><div class="shell process-grid"><div><p class="kicker">03 / How we work</p><h2>Good people.<br>Clear process.</h2></div><div class="steps"><article class="step"><span class="kicker">01</span><h3>Find the right problem.</h3><p>We learn from the people doing the work. Together, we choose one valuable problem, a practical scope, and a clear way to judge the result.</p></article><article class="step"><span class="kicker">02</span><h3>Deploy a useful solution.</h3><p>Configure what already works, connect the gaps, and build what is missing. Your team tries the real thing early and helps shape it.</p></article><article class="step"><span class="kicker">03</span><h3>Make it stick.</h3><p>We help your team use what we build, check the result, and improve it. Ongoing support has a clear scope, just like the first project.</p></article></div></div></section>'''
studio='''<section class="chapter studio" id="studio"><div class="shell"><div class="studio-grid"><div class="studio-copy"><p class="kicker">04 / The studio</p><h2>Small team.<br>Deep experience.</h2><p>We’re Nate and Josh McGuire. Our model pairs senior engineering with a business and product partner who stays close to your team.</p><p>We learn how the work happens, decide what is worth building, and stay involved through launch and adoption.</p></div><div class="team"><article class="person"><img src="/assets/nate.jpg" alt="Nate McGuire" width="400" height="400" loading="lazy"><h3>Nate McGuire</h3><p class="kicker">Founder · Design &amp; engineering</p><p>Distinguished Engineer. Founder of Mayven Studios. More than 15 years building and shipping digital products.</p></article><article class="person"><img src="/assets/josh.png" alt="Josh McGuire" width="560" height="584" loading="lazy"><h3>Josh McGuire</h3><p class="kicker">Delivery · Project operations</p><p>Certified Scrum Master. Nine years of delivery experience across Mayven, Big Four consulting, and venture-backed teams.</p></article></div></div><div class="experience"><p>Our experience includes work at Mayven Studios for teams at:</p><div><span>Google</span><span>Facebook</span><span>IBM</span><span>Airbnb</span><span>Andreessen Horowitz</span></div></div></div></section>'''
contact='''<section class="chapter contact" id="contact"><div class="shell contact-grid"><div><p class="kicker">05 / Start a conversation</p><h2>What are we<br>building next?</h2><p>A new business, a better product, a civic project with a deadline. Tell us what you have in mind.</p><a class="link" href="mailto:contact@eastbayprojects.com">contact@eastbayprojects.com <span>↗</span></a></div><form class="preview-form"><label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>Email<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label class="full">What do you have in mind?<textarea name="message" required minlength="10" maxlength="4000" placeholder="The idea, the audience, and when you need it."></textarea></label><button class="primary full" type="submit">Send project details <span aria-hidden="true">↗</span></button><p class="form-note full">Design preview: this form demonstrates the experience. No details are sent or stored.</p><p class="preview-message" role="status" hidden></p></form></div></section>'''
footer='<footer class="shell footer"><span>© 2026 East Bay Projects</span><span>Austin + Washington, DC · Made in the USA</span><a href="/directions.html">Explore all ten directions ↗</a></footer>'
for c in CONCEPTS:
 if c['id']=='editorial':continue
 path=OUT/c['id'];path.mkdir()
 # The substance is shared; the visual hierarchy and layout belong to each direction.
 html=head(c['name'])+f'<body class="concept {c["id"]}">'+nav()+'<main id="main">'+heroes[c['id']]+work+services+process+studio+contact+'</main>'+footer+dock(c['id'])+'</body></html>'
 (path/'index.html').write_text(html)
for p in (OUT/'editorial').glob('*.html'):
 s=p.read_text()
 s=re.sub(r'<script>.*?</script>','',s,flags=re.S)
 s=re.sub(r'<link\s+rel="canonical"[^>]*>','',s)
 s=s.replace('/nate.jpg','/assets/nate.jpg').replace('/editorial/contact\"','/editorial/contact.html\"')
 s=re.sub(r'<form[^>]*>',lambda m:re.sub(r' action="[^"]*"| method="[^"]*"','',m.group()),s)
 s=s.replace('</head>','<link href="/explore.css" rel="stylesheet"><script>if(new URLSearchParams(location.search).has(\'embed\'))document.documentElement.classList.add(\'embedded\');</script><script src="/explore.js" defer></script></head>')
 s=s.replace('</body>',dock('editorial')+'</body>')
 if p.name=='contact.html':
  s=s.replace('id="lead-form"','id="lead-form" data-preview-form').replace('</form>','<p class="preview-message" role="status" hidden></p><p class="preview-form-disclaimer">Design preview: no details are sent or stored.</p></form>')
 p.write_text(s)
# Forms are inert until the preview-only submit handler is attached.
for page in OUT.rglob('*.html'):
 text=page.read_text()
 text=re.sub(r'<form(?=[ >])', '<form inert', text)
 page.write_text(text)
# Comparison hub uses actual page screenshots, generated during visual QA.
cards=[]
for c in CONCEPTS:
 cards.append(f'''<article class="direction-card"><a class="direction-thumb" style="background:{c['background']}" href="/{c['id']}/"><img src="/assets/previews/{c['id']}.webp" width="1440" height="1000" alt="Preview of {c['name']}" loading="lazy"><span class="thumb-open">Open direction ↗</span></a><div class="card-meta"><span>{c['number']} / {c['short']}</span><button class="shortlist-button" data-shortlist="{c['id']}" aria-pressed="false" aria-label="Shortlist {c['name']}">☆</button></div><h2><a href="/{c['id']}/">{c['name']}</a></h2><p class="card-position">{c['position']}</p><p class="card-description">{c['description']}</p><div class="card-bottom"><button data-compare-pick="{c['id']}" aria-pressed="false">+ Compare</button><a href="/{c['id']}/">Explore the direction <span>↗</span></a></div></article>''')
gallery=head('Ten Directions','explore.css')+'''<body class="exploration"><header class="lab-header lab-wrap"><a class="lab-brand" href="/">east bay projects.<span>Design exploration</span></a><span class="test-label"><i></i> Test site · Production unchanged</span></header><main class="lab-wrap"><section class="lab-intro"><div><p class="lab-kicker">A study in ten directions / September 2026</p><h1>One studio.<br><em>Ten possibilities.</em></h1></div><div class="lab-intro-copy"><p>The same agency. Ten different ways to express it.</p><p>Explore complete pages, shortlist what feels right, and compare two directions side by side. Each brings businesses, founders, and civic work into one story.</p><a href="/editorial/" class="lab-start">Start exploring <span>↗</span></a></div></section><div class="gallery-tools"><p><strong>10 directions</strong> · Each is a working prototype</p><div><button class="shortlist-filter" aria-pressed="false">Show shortlist <span data-shortlist-count>0</span></button><button class="compare-launch" disabled>Compare selected <span data-compare-count>0 / 2</span></button></div></div><p class="shortlist-empty" hidden>No shortlisted directions yet. Use the star on any direction to save it here.</p><section class="directions-grid" aria-label="Design directions">'''+''.join(cards)+'''</section><section class="review-notes"><h2>Pick the feeling.<br>Then we refine the details.</h2><div><p>The goal is to choose a direction, or a useful combination: one design’s typography, another’s project presentation, a third’s tone.</p><p>Your shortlist stays in this browser. Prototype forms do not submit or store inquiries. The live East Bay Projects site is unchanged.</p></div></section></main><footer class="lab-footer lab-wrap"><span>East Bay Projects / Design exploration</span><a href="https://eastbayprojects.com/" target="_blank" rel="noopener noreferrer">Current live site ↗</a></footer></body></html>'''
(OUT/'index.html').write_text(gallery)
opts=''.join(f'<option value="{c["id"]}">{c["number"]} · {c["name"]}</option>' for c in CONCEPTS)
compare=head('Compare Directions','explore.css')+f'''<body class="comparison"><header class="compare-header"><a href="/directions.html">↖ All directions</a><h1>Side by side.</h1><div class="compare-sizes" role="group" aria-label="Preview width"><button data-frame-size="desktop" aria-pressed="true">Desktop</button><button data-frame-size="phone" aria-pressed="false">Phone</button></div></header><main class="compare-grid"><section class="compare-pane"><div class="pane-toolbar"><label>Left direction <select data-compare-side="left">{opts}</select></label><a data-open-side="left" href="/editorial/" target="_blank">Open ↗</a></div><div class="frame-stage"><iframe title="Left design preview" data-frame="left" src="/editorial/?embed=1"></iframe></div></section><section class="compare-pane"><div class="pane-toolbar"><label>Right direction <select data-compare-side="right">{opts}</select></label><a data-open-side="right" href="/swiss/" target="_blank">Open ↗</a></div><div class="frame-stage"><iframe title="Right design preview" data-frame="right" src="/swiss/?embed=1"></iframe></div></section></main><p class="compare-note">Scroll each preview independently. Use Open to explore a direction at full width.</p></body></html>'''
(OUT/'compare.html').write_text(compare)
(OUT/'privacy.html').write_text(head('Preview Notes','explore.css')+'<body class="exploration"><main class="lab-wrap review-notes"><div><h1>Design preview.</h1><p>The inquiry forms on this test site do not send or store details. Shortlists are saved only in this browser.</p><a href="/">Return to all directions ↗</a></div></main></body></html>')
(OUT/'robots.txt').write_text('User-agent: *\nDisallow: /\n')
(OUT/'_headers').write_text('/*\n  X-Robots-Tag: noindex, nofollow\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Content-Type-Options: nosniff\n')
shutil.copytree(SOURCE/'current',OUT/'current',dirs_exist_ok=True)
shutil.copy2(OUT/'index.html', OUT/'directions.html')
shutil.copy2(OUT/'current/index.html', OUT/'index.html')
print(f'Built current-site civic revision plus 10 archived directions in {OUT}')
